project/careers/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from main import views
from .views import *

app_name = "careers"

urlpatterns = [
    path('career-info/', career_info, name="career-info"),
    path('new-careerinfo/', new_careerinfo, name="new-careerinfo"),
    path('careerinfo-create/', careerinfo_create, name="careerinfo-create"),
    path('careerinfo-detail/<int:id>/', careerinfo_detail, name="careerinfo-detail"),
    path('careerinfo-delete/<int:id>/', careerinfo_delete, name="careerinfo-delete"),
    path('careerinfotag-careerinfos/<int:careerinfotag_id>/', careerinfotag_careerinfos, name="careerinfotag-careerinfos"),
    path('ci_bms/<int:careerinfo_id>', ci_bms, name="ci_bms"),
    path('career-program/', career_program, name="career-program"),
    path('new-careerprogram/', new_careerprogram, name="new-careerprogram"),
    path('careerprogram-create/', careerprogram_create, name="careerprogram-create"),
    path('careerprogram-detail/<int:id>/', careerprogram_detail, name="careerprogram-detail"),
    path('careerprogram-delete/<int:id>/', careerprogram_delete, name="careerprogram-delete"),
    path('careerprogramtag-careerprograms/<int:careerprogramtag_id>/', careerprogramtag_careerprograms, name="careerprogramtag-careerprograms"),
    path('cp_bms/<int:careerprogram_id>', cp_bms, name="cp_bms"),
    path('edu-info/', edu_info, name="edu-info"),
    path('new-eduinfo/', new_eduinfo, name="new-eduinfo"),
    path('eduinfo-create/', eduinfo_create, name="eduinfo-create"),
    path('eduinfo-detail/<int:id>/', eduinfo_detail, name="eduinfo-detail"),
    path('eduinfo-delete/<int:id>/', eduinfo_delete, name="eduinfo-delete"),
    path('eduinfotag-eduinfos/<int:eduinfotag_id>/', eduinfotag_eduinfos, name="eduinfotag-eduinfos"),
    path('ei_bms/<int:eduinfo_id>', ei_bms, name="ei_bms"),
    path('careerinfo-detail/<int:id>/apply/', apply_careerinfo, name="apply_careerinfo"),
    path('careerprogram-detail/<int:id>/apply/', apply_careerprogram, name="apply_careerprogram"),
    path('eduinfo-detail/<int:id>/apply/', apply_eduinfo, name="apply_eduinfo"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/community/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name = "community"
urlpatterns = [
    path('free-board/', free_board, name='free-board'),
    path('move-board/', move_board, name='move-board'),
    path('new-free/', new_free, name="new-free"),
    path('free-create/', free_create, name="free-create"),
    path('free-detail/<int:id>/', free_detail, name='free-detail'),
    path('free-edit/<int:id>/', free_edit, name="free-edit"),
    path('free-update/<int:id>/', free_update, name="free-update"),
    path('free-delete/<int:id>/', free_delete, name="free-delete"),
    path('new-move/', new_move, name="new-move"),
    path('move-create/', move_create, name="move-create"),
    path('move-detail/<int:id>/', move_detail, name='move-detail'),
    path('move-edit/<int:id>/', move_edit, name="move-edit"),
    path('move-update/<int:id>/', move_update, name="move-update"),
    path('move-delete/<int:id>/', move_delete, name="move-delete"),
    path('freetag-list', freetag_list, name="freetag-list"),
    path('movetag-list', movetag_list, name="movetag-list"),
    path('freetag-frees/<int:freetag_id>', freetag_frees, name="freetag-frees"),
    path('movetag-moves/<int:movetag_id>', movetag_moves, name="movetag-moves"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/main/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name = "main"
urlpatterns = [
    path('', intro, name='intro'),
    path('first-screen', first_screen, name='first-screen'),
    path('mainpage', mainpage, name='mainpage'),
    path('mentor-start', mentor_start, name='mentor-start'),
    path('mentor-list/', mentor_list, name='mentor-list'),
    path('mentor-info/<int:id>/', mentor_info, name='mentor-info'),
    path('mentor-create/', mentor_create, name='mentor-create'),
    path('mentor-enroll/', mentor_enroll, name='mentor-enroll'),
    path('mentor-relation-create/<int:id>/', mentor_relation_create, name='mentor-relation-create'),
    path('mentor-ask/<int:id>/', mentor_ask, name='mentor-ask'),
    path('create-menti/<int:id>', create_menti, name="create-menti"),
    path('follow/<int:id>/', follow, name='follow'),
    path('follow2/<int:id>/', follow2, name='follow2'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('users/', include('users.urls')),
    path('careers/', include('careers.urls')),
    path('community/', include('community.urls')),
] 

project/users/urls.py
from django.urls import path
from .views import *

app_name = "users"
urlpatterns = [
    path('mypage/<int:id>/', mypage, name="mypage"),
    path('edit_portfolio/', edit_portfolio, name='edit_portfolio'),
    path('portfolio/<int:id>', view_portfolio, name='portfolio'),
    path('follow-list/<int:id>', follow_list, name="follow-list"),
    path('bookmark/<int:id>', bookmark, name="bookmark"),
    path('my-writing/<int:id>', my_writing, name="my-writing"),
    path('mentoring/<int:id>', mentoring, name="mentoring"),
    path('career-now/<int:id>', career_now, name="career-now"),
    path('menti-list/<int:id>/', menti_list, name="menti-list"),
    path('mentoring-state/<int:id>', mentoring_state, name="mentoring-state"),
    path('cibms/', cibm_list, name="cibm_list"),
    path('cpbms/', cpbm_list, name="cpbm_list"),
    
    path('eibms/', eibm_list, name="eibm_list"),
    path('ci_bms/<int:careerinfo_id>/', ci_bms, name='ci_bms'),
    path('cp_bms/<int:careerprogram_id>/', cp_bms, name='cp_bms'),
    path('ei_bms/<int:eduinfo_id>/', ei_bms, name='ei_bms'),
    path('ciapply/', ciapply, name="ciapply"),
    path('cpapply/', cpapply, name="cpapply"),
    path('eiapply/', eiapply, name="eiapply"),
]

project/users/models.py
from django.db import models
from django.contrib.auth.models import User

class Education(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Experience(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Project(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Certification(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Portfolio(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    introduction = models.TextField(max_length=500)
    education = models.ManyToManyField(Education)
    experience = models.ManyToManyField(Experience)
    projects = models.ManyToManyField(Project)
    certifications = models.ManyToManyField(Certification)

    def __str__(self):
        return self.user.username

project/users/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from .models import Portfolio, Education, Experience, Project, Certification
from accounts.models import Profile
from main.models import Mentor, Relation_mentor, Menti
from community.models import Free, Move
from careers.models import Careerinfo, Careerprogram, Eduinfo, Ciapply, Cpapply, Eiapply

def mypage(request, id):
    user = get_object_or_404(User, pk=id)
    profile, created = Profile.objects.get_or_create(user=user)
    portfolio, created = Portfolio.objects.get_or_create(user=user)
    following_count = user.mentor_followings.count()

    context = {
        'user': user,
        'profile': profile,
        'portfolio': portfolio,
        'following_count': following_count,
    }
    
    return render(request, 'users/mypage.html', context)

def follow_list(request, id):
    user = get_object_or_404(User, pk=id)
    context = {
        'followings': user.mentor_followings.all(),
        'followers': user.profile.followers.all()
    }
    return render(request, 'users/follow_list.html', context)

def bookmark(request, id):
    return render(request, 'users/bookmark.html')

def ciapply(request):
    ci_apply=Ciapply.objects.filter(user=request.user)
    return render(request, 'users/ciapply.html', {'ci_apply': ci_apply})

def cpapply(request):
    cp_apply=Cpapply.objects.filter(user=request.user)
    return render(request, 'users/cpapply.html', {'cp_apply': cp_apply})

def eiapply(request):
    ei_apply=Eiapply.objects.filter(user=request.user)
    return render(request, 'users/eiapply.html', {'ei_apply': ei_apply})

def edit_portfolio(request):
    portfolio, created = Portfolio.objects.get_or_create(user=request.user)
    if request.method == 'POST':
        title = request.POST.get('title', '')
        introduction = request.POST.get('introduction', '')
        education_list = request.POST.getlist('education', [])
        experience_list = request.POST.getlist('experience', [])
        projects_list = request.POST.getlist('projects', [])
        certifications_list = request.POST.getlist('certifications', [])

        portfolio.title = title
        portfolio.introduction = introduction

        portfolio.education.clear()
        for edu in education_list:
            if edu:  # 비어 있지 않은지 확인
                education, created = Education.objects.get_or_create(name=edu)
                portfolio.education.add(education)

        portfolio.experience.clear()
        for exp in experience_list:
            if exp:  # 비어 있지 않은지 확인
                experience, created = Experience.objects.get_or_create(name=exp)
                portfolio.experience.add(experience)

        portfolio.projects.clear()
        for proj in projects_list:
            if proj:  # 비어 있지 않은지 확인
                project, created = Project.objects.get_or_create(name=proj)
                portfolio.projects.add(project)

        portfolio.certifications.clear()
        for cert in certifications_list:
            if cert:  # 비어 있지 않고 문자열인지 확인
                certification, created = Certification.objects.get_or_create(name=cert)
                portfolio.certifications.add(certification)

        portfolio.save()

        # 디버깅을 위해 저장된 데이터를 출력합니다.
        print('Title:', portfolio.title)
        print('Introduction:', portfolio.introduction)
        print('Education:', [edu.name for edu in portfolio.education.all()])
        print('Experience:', [exp.name for exp in portfolio.experience.all()])
        print('Projects:', [proj.name for proj in portfolio.projects.all()])
        print('Certifications:', [cert.name for cert in portfolio.certifications.all()])

        return redirect('users:portfolio', id=request.user.id)

    return render(request, 'users/edit_portfolio.html', {'portfolio': portfolio})

def view_portfolio(request, id):
    user = get_object_or_404(User, pk=id)
    portfolio, created = Portfolio.objects.get_or_create(user=user)
    portfolio = get_object_or_404(Portfolio, user=user)
    education = portfolio.education.all()
    experience = portfolio.experience.all()
    projects = portfolio.projects.all()
    certifications = portfolio.certifications.all()
    return render(request, 'users/portfolio.html', {
        'portfolio': portfolio,
        'education': education,
        'experience': experience,
        'projects': projects,
        'certifications': certifications
    })

def my_writing(request, id):
    user = User.objects.get(pk=id)
    username = request.user
    my_writes_free = Free.objects.filter(writer = username)
    my_writes_move = Move.objects.filter(writer = username)
    my_writes_careerinfo = Careerinfo.objects.filter(writer = username)
    context = {
        'user' : user,
        'my_writes_free' : my_writes_free,
        'my_writes_move' : my_writes_move,
        'my_writes_careerinfo' : my_writes_careerinfo
    }
    return render(request, 'users/my_writing.html', context)

def mentoring(request, id):
    user = get_object_or_404(User, pk=id)
    # mentor_state = Relation_mentor.objects.filter(menti=user)
    mentor = Menti.objects.filter(user=user)
    mentor_state = Relation_mentor.objects.filter(menti=user)
    context = {
        # 'menti_ship': user.menti_ship.all(),
        # 'mentor_state':mentor_state.all(),
        'mentor':mentor.all(),
    }
    return render(request, 'users/mentoring.html', context)

def menti_list(request, id):
    user = get_object_or_404(User, pk=id)
    mentors = Mentor.objects.all()
    mentor = Menti.objects.filter(user=user)
    # mentors = Mentor.objects.filter(user_id=id)
    menti = []
    for mentor in mentors:
        if mentor.user_id == id:
            m = Menti.objects.filter(mentor=mentor)
            menti.extend(m)
    return render(request, 'users/menti_list.html', {
        'menti':menti,
        'mentor':mentor
        })

def mentoring_state(request, id):
    user = get_object_or_404(User, pk=id)
    if request.method == 'POST':
        mentorship_id = request.POST.get('mentorship_id')
        state = request.POST.get('state')
        try:
            mentoring = Menti.objects.get(pk=mentorship_id)
            if state == '거절':
                mentoring.state = "거절"
            elif state == '수락':
                mentoring.state = '수락'
            else:
                mentoring.state = '대기'
            mentoring.save()  # Save the state change
        except Relation_mentor.DoesNotExist:
            # Handle the case where the mentorship does not exist
            pass
    return redirect('users:mentoring', user.id)

def career_now(request, id):
    return render(request, 'users/career_now.html')



def cibm_list(request):
    user = request.user
    cibms = user.ci_bms.all()
    return render(request, 'users/cibm.html', {'cibms': cibms})

def cpbm_list(request):
    user = request.user
    cpbms = user.cp_bms.all()
    return render(request, 'users/cpbm.html', {'cpbms': cpbms})

def eibm_list(request):
    user = request.user
    eibms = user.ei_bms.all()
    return render(request, 'users/eibm.html', {'eibms': eibms})

def ci_bms(request, careerinfo_id):
    careerinfo = get_object_or_404(Careerinfo, id=careerinfo_id)
    if request.user in careerinfo.ci_bm.all():
        careerinfo.ci_bm.remove(request.user)
        careerinfo.cibm_count-=1
        careerinfo.save()
    else:
        careerinfo.ci_bm.add(request.user)
        careerinfo.cibm_count +=1
        careerinfo.save()
    return redirect('users:cibm_list')

def cp_bms(request, careerprogram_id):
    careerprogram = get_object_or_404(Careerprogram, id=careerprogram_id)
    if request.user in careerprogram.cp_bm.all():
        careerprogram.cp_bm.remove(request.user)
        careerprogram.cpbm_count-=1
        careerprogram.save()
    else:
        careerprogram.cp_bm.add(request.user)
        careerprogram.cpbm_count +=1
        careerprogram.save()
    return redirect('users:cpbm_list')

def ei_bms(request, eduinfo_id):
    eduinfo = get_object_or_404(Eduinfo, id=eduinfo_id)
    if request.user in eduinfo.ei_bm.all():
        eduinfo.ei_bm.remove(request.user)
        eduinfo.eibm_count-=1
        eduinfo.save()
    else:
        eduinfo.ei_bm.add(request.user)
        eduinfo.eibm_count +=1
        eduinfo.save()
    return redirect('users:eibm_list') 

project/users/templates/users/ciapply.html
{% extends 'base_with_nav.html' %} {% load static %} {% block content %}

<link
rel="stylesheet"
type="text/css"
href="{% static 'css/users/ciapply.css'%}"
/>

<div class="screen">
  <div class="main">
    <div class="body">

        <div class="nav">
            <div class="left" style="z-index: 1;">
                <a href="{% url 'main:mainpage' %}">
        <img src="{% static 'images/arrow-24.png' %}" width='32px' height='32px'>
                </a>
            </div>
            <div><p class="color_28 title_text" style="text-align: center;">커리어 신청 현황</p></div>
            <div style="width: 32px;"></div>
        </div>


        <div class="active">
            <div class='act3'>
            <a class="active3" href="{% url 'users:ciapply' %}">채용</a><div class='line3'></div>
            </div>
            <div class='act1'>
            <a class="active1" href="{% url 'users:cpapply' %}">취업 프로그램</a><div class='line1'></div>
            </div>
            <div class='act2'>
            <a class="active2" href="{% url 'users:eiapply' %}">교육</a><div class='line2'></div>
            </div>
        </div>
        
        <div class="application">
            {% for application in ci_apply %}
                <a class='detail' href="{% url 'careers:careerinfo-detail' application.careerinfo.id %}">
                    {% comment %} area에 템플릿 언어 넣어야함 {% endcomment %}
                    <div class='areadate'>
                        <div class='area'>{{ application.field }}</div>
                        <div class='date'>{{ application.application_date|date:"Y/m/d" }}</div>                            
                    </div>
                    <div class='place'>{{ application.careerinfo.company }}</div>
                    <div class='title'>{{ application.careerinfo.title }}</div>
                    <div class='line'></div>
                </a>
            {% endfor %}
        
        </div>
    </div>
  </div>
</div>
{% endblock %}

project/users/templates/users/cpapply.html
{% extends 'base_with_nav.html' %} {% load static %} {% block content %}

<link
rel="stylesheet"
type="text/css"
href="{% static 'css/users/cpapply.css'%}"
/>

<div class="screen">
  <div class="main">
    <div class="body">

        <div class="nav">
            <div class="left" style="z-index: 1;">
                <a href="{% url 'main:mainpage' %}">
        <img src="{% static 'images/arrow-24.png' %}" width='32px' height='32px'>
                </a>
            </div>
            <div><p class="color_28 title_text" style="text-align: center;">커리어 신청 현황</p></div>
            <div style="width: 32px;"></div>
        </div>


        <div class="active">
            <div class='act1'>
            <a class="active1" href="{% url 'users:ciapply' %}">채용</a><div class='line1'></div>
            </div>
            <div class='act3'>
            <a class="active3" href="{% url 'users:cpapply' %}">취업 프로그램</a><div class='line3'></div>
            </div>
            <div class='act2'>
            <a class="active2" href="{% url 'users:eiapply' %}">교육</a><div class='line2'></div>
            </div>
        </div>
        
        <div class="application">
            {% for application in cp_apply %}
                <a class='detail' href="{% url 'careers:careerprogram-detail' application.careerprogram.id %}">
                    {% comment %} area에 템플릿 언어 넣어야함 {% endcomment %}
                    <div class='areadate'>
                        <div class='area'>{{ application.careerprogram.filed }}</div>
                        <div class='date'>{{ application.application_date|date:"Y/m/d" }}</div>                            
                    </div>
                        <div class='place'>{{ application.careerprogram.place }}</div>
                        <div class='title'>{{ application.careerprogram.title }}</div>
                        <div class='line'></div>
                </a>
            {% endfor %}
        
        </div>
    </div>
  </div>
</div>
{% endblock %}

project/users/templates/users/eiapply.html
{% extends 'base_with_nav.html' %} {% load static %} {% block content %}

<link
rel="stylesheet"
type="text/css"
href="{% static 'css/users/eiapply.css'%}"
/>

<div class="screen">
	<div class="main">
    <div class="body">

			<div class="nav">
				<div class="left" style="z-index: 1;">
					<a href="{% url 'main:mainpage' %}">
            <img src="{% static 'images/arrow-24.png' %}" width='32px' height='32px'>
					</a>
				</div>
				<div><p class="color_28 title_text" style="text-align: center;">커리어 신청 현황</p></div>
				<div style="width: 32px;"></div>
			</div>


            <div class="active">
              <div class='act1'>
                <a class="active1" href="{% url 'users:ciapply' %}">채용</a><div class='line1'></div>
              </div>
              <div class='act2'>
                <a class="active2" href="{% url 'users:cpapply' %}">취업 프로그램</a><div class='line2'></div>
              </div>
              <div class='act3'>
                <a class="active3" href="{% url 'users:eiapply' %}">교육</a><div class='line3'></div>
              </div>
            </div>
            
            <div class="application">
                {% for application in ei_apply %}
                    <a class='detail' href="{% url 'careers:eduinfo-detail' application.eduinfo.id %}">
                      {% comment %} area에 템플릿 언어 넣어야함 {% endcomment %}
                        <div class='areadate'>
                          <div class='area'>{{eduinfo.field}}</div>
                          <div class='date'>{{ application.application_date|date:"Y/m/d" }}</div>                            
                        </div>
                          <div class='place'>{{ application.eduinfo.place }}</div>
                          <div class='title'>{{ application.eduinfo.title }}</div>
                          <div class='line'></div>
                    
                    </a>
                {% endfor %}
            </div>
    </div>
  </div>
</div>
{% endblock %}

project/users/templates/users/eibm.html
{% extends 'base_with_nav.html' %} {% load static %} {% block content %}

<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/users/bookmark.css'%}"
/>

<div class="screen">
	<div class="main">
    <div class="body">
			<div class="nav">
				<div class="left" style="z-index: 1;">
					<a href="{% url 'main:mainpage' %}">
            <img src="{% static 'images/arrow-24.png' %}" width='32px' height='32px'>
					</a>
				</div>
				<div><p class="color_28 title_text" style="text-align: center;">북마크 리스트</p></div>
				<div style="width: 32px;"></div>
			</div>
      <div class="active">
        <div class="act1"><a class="active1" href="{% url 'users:cibm_list' %}">채용정보</a><div class="line1"></div></div>
        <div class="act2"><a class="active1_2" href="{% url 'users:cpbm_list' %}">채용프로그램</a><div class="line2"></div></div>
        <div class="act3"><a class="active3" href="{% url 'users:eibm_list' %}">교육정보</a><div class="line3"></div></div>
      </div>

      <div class="application">
        {% for eduinfo in eibms %}
        <a class="detail" href="{% url 'careers:eduinfo-detail' eduinfo.id %}">
          <div>
            <div class="areadate" style="padding-bottom: 0.25rem;">
              <div class="area">{{ eduinfo.field }}</div>
            </div>
            <div class="place">{{ eduinfo.place }}</div>
            <div class="title">{{ eduinfo.title }}</div>
          </div>
          <div style="display: flex; flex-direction: column;">
            <p class="hi">채용정보</p>
            <form style="display: flex; flex-direction: row-reverse;" action="{% url 'users:ei_bms' eduinfo.id %}">
              <button>
                <img src="{% static 'images/filled_bookmark.png'%}" width="30px">
              </button>
            </form>
          </div>
        </a>
        {% endfor %}
      </div>
    </div>
  </div>
</div>



<script>
  document.addEventListener("DOMContentLoaded", function() {
      document.querySelectorAll('.navbar a').forEach(function(link) {
          link.addEventListener('click', function(event) {
              event.preventDefault();
              window.location.href = link.getAttribute('href');
          });
      });
  });
</script>


{% endblock %}



<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>채용 정보 북마크</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }
        .navbar {
            overflow: hidden;
            background-color: #333;
        }
        .navbar a {
            float: left;
            display: block;
            color: white;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }
        .navbar a:hover {
            background-color: #ddd;
            color: black;
        }
    </style>
    <script>
        document.addEventListener("DOMContentLoaded", function() {
            document.querySelectorAll('.navbar a').forEach(function(link) {
                link.addEventListener('click', function(event) {
                    event.preventDefault();
                    window.location.href = link.getAttribute('href');
                });
            });
        });
    </script>
</head>
<body>
    <div class="navbar">
        <a href="{% url 'users:cibm_list' %}">채용정보</a>
        <a href="{% url 'users:cpbm_list' %}">채용프로그램</a>
        <a href="{% url 'users:eibm_list' %}">교육정보</a>
    </div>
<h1>내 북마크</h1>
<ul>
    {% for careerinfo in cibms %}
        <li>
            <a href="{% url 'careers:careerinfo-detail' careerinfo.id %}">{{ careerinfo.title }}</a>
            <p>{{ careerinfo.company }}</p>
            <p>{{ careerinfo.startline }}|{{careerinfo.deadline}}</p>
        </li>
    {% endfor %}
</ul>

project/users/templates/users/my_writing.html
{% extends 'base.html' %} {% load static %} {% block content %}

<link
rel="stylesheet"
type="text/css"
href="{% static 'css/users/my_writing.css'%}"
/>

<div class="screen">
<div class="main">
  <div class="body">
    
      <div class="nav">
        <div class="left" style="z-index: 1;">
          <a href="{% url 'main:mainpage' %}">
            <img src="{% static 'images/arrow-24.png' %}" width='32px' height='32px'>
          </a>
        </div>
        <div><p class="color_28 title_text" style="text-align: center;">내가 쓴 글</p></div>
        <div style="width: 32px;"></div>
      </div>

          {% comment %} 이직게시판 부분에 area 넣어야함 (분야) {% endcomment %}

    <div class='groupmy'>
      {% if request.user == user %}

        <div class='my'>
            {% for free in my_writes_free %} 
                <div class='where'>자유게시판</div>
            <a href="{% url 'community:free-detail' free.id %}"> 
                <div class='title'>{{free.title}}</div>
            </a>
                <div class='content'>{{free.content}}</div>
                <div class='date'>{{free.pub_date}}</div>
                <div class='line'></div>
            {% endfor %}
        </div>
      
        <div class='my'>
            {% for move in my_writes_move %}
            <div class='wherearea'>
                <div class='where'>이직게시판</div>
                <div class='area'>| IT개발/데이터****</div>
            </div>
            <a href="{% url 'community:move-detail' move.id %}">
                <div class='title'>{{move.title}}</div>
            </a>
                <div class='content'>{{move.content}}</div>
                <div class='date'>{{move.pub_date}}</div>
                <div class='line'></div>
            {% endfor %}
        </div>


        <div class='my'>
            {% for careerinfo in my_writes_careerinfo %}
                <div class='where'>커리어게시판</div>   
            <a href="{% url 'careers:careerinfo-detail' careerinfo.id %}"> 
                <div class='title'>{{careerinfo.title}}</div>
            </a>
                <div class='content'>{{careerinfo.content}}</div>
                <div class='date'>{{careerinfo.pub_date}}</div>
                <div class='line'></div>
            {% endfor %}
        </div>

      {% endif %}
    </div>

  </div>
</div>
</div>

{% endblock %}

project/users/templates/users/mypage.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ user.username }}님의 마이페이지</title>
</head>
<body>
    <h1>{{ profile.user_name }}님의 마이페이지</h1>
    <p>user: {{ user.username }}</p>
    <p>전화번호: {{ profile.user_phone }}</p>
    <h2>포트폴리오</h2>
    <p>제목: {{ portfolio.title }}</p>
    <p>소개: {{ portfolio.introduction }}</p>
    <p>학력: {{ portfolio.education }}</p>
    <p>경력: {{ portfolio.experience }}</p>
    <p>프로젝트: {{ portfolio.projects }}</p>
    <p>자격증/수상: {{ portfolio.certifications }}</p>
    {% if profile.user_profile %}
        <img src="{{ profile.user_profile.url }}" alt="프로필 사진">
    {% else %}
        <p>프로필 사진이 없습니다.</p>
    {% endif %}
    <a href="{% url 'users:edit_portfolio' %}">포트폴리오 편집</a>
    <a href="{% url 'users:follow-list' user.id %}">팔로잉{{ following_count }}</a>
</body>
</html>