project/accounts/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name = "accounts"
urlpatterns = [
    path('login/', login, name="login"),
    path('logout/', logout, name="logout"),
    path('signup/', signup, name="signup"),
    path('signup2/', signup2, name="signup2"),
    path('signup3/', signup3, name="signup3"),
    path('update-profile/<int:id>', update_profile, name="update-profile"),
    path('finishjoin/', finishjoin, name="finishjoin"),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/main/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name = "main"
urlpatterns = [
    path('', intro, name='intro'),
    path('first-screen', first_screen, name='first-screen'),
    path('mainpage', mainpage, name='mainpage'),
    path('mentor-start', mentor_start, name='mentor-start'),
    path('mentor-list/', mentor_list, name='mentor-list'),
    path('mentor-info/<int:id>/', mentor_info, name='mentor-info'),
    path('mentor-create/', mentor_create, name='mentor-create'),
    path('mentor-enroll/', mentor_enroll, name='mentor-enroll'),
    path('mentor-relation-create/<int:id>/', mentor_relation_create, name='mentor-relation-create'),
    path('mentor-ask/<int:id>/', mentor_ask, name='mentor-ask'),
    path('create-menti/<int:id>', create_menti, name="create-menti"),
    path('follow/<int:id>/', follow, name='follow'),
    path('follow2/<int:id>/', follow2, name='follow2'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('users/', include('users.urls')),
    path('careers/', include('careers.urls')),
    path('community/', include('community.urls')),
] 

project/users/urls.py
from django.urls import path
from .views import *

app_name = "users"
urlpatterns = [
    path('mypage/<int:id>/', mypage, name="mypage"),
    path('edit_portfolio/', edit_portfolio, name='edit_portfolio'),
    path('portfolio/<int:id>', view_portfolio, name='portfolio'),
    path('follow-list/<int:id>', follow_list, name="follow-list"),
    path('bookmark/<int:id>', bookmark, name="bookmark"),
    path('my-writing/<int:id>', my_writing, name="my-writing"),
    path('mentoring/<int:id>', mentoring, name="mentoring"),
    path('career-now/<int:id>', career_now, name="career-now"),
    path('menti-list/<int:id>/', menti_list, name="menti-list"),
    path('mentoring-state/<int:id>', mentoring_state, name="mentoring-state"),
    path('cibms/', cibm_list, name="cibm_list"),
    path('cpbms/', cpbm_list, name="cpbm_list"),
    
    path('eibms/', eibm_list, name="eibm_list"),
    path('ci_bms/<int:careerinfo_id>/', ci_bms, name='ci_bms'),
    path('cp_bms/<int:careerprogram_id>/', cp_bms, name='cp_bms'),
    path('ei_bms/<int:eduinfo_id>/', ei_bms, name='ei_bms'),
    path('ciapply/', ciapply, name="ciapply"),
    path('cpapply/', cpapply, name="cpapply"),
    path('eiapply/', eiapply, name="eiapply"),
]

project/project/templates/shared/_navbar.html
{% load static %}
<link
  rel="stylesheet"
  type=""
  href="{% static 'css/shared/navbar.css' %}"
/>

<div class="screen">
  <div class="main">
    <div class="column"> 
      <div class="navbar" id="navbar">
        <div class="row_space_between">
          <div style="width: 32px;"></div>
          <div class="row">
            <a class="row" href="{% url 'main:mainpage' %}">
              <img src="{% static 'images/profile_key.png' %}" width="32px" height="32px">
            </a>
            <img src="{% static 'images/person.png' %}" width="32px" height="32px" id="btn_open_mypage">
          </div>
        </div>
      </div>
      <div class="navbar2" id="navbar2">
        <div class="row_space_between">
          <div style="width: 32px;"> 
            <a href="{% url 'accounts:logout' %}" position='fixed'>
            <img class='logout' src="{% static 'images/로그아웃2.png' %}" width="24px" height="24px">
          </a>
          </div>
          <a class="row" href="{% url 'main:mainpage' %}">
            <img src="{% static 'images/profile_key.png' %}" width="32px" height="32px">
            <p class="color_1E title_font">MY PAGE</p>
          </a>
          <div>
            <img src="{% static 'images/signx.png' %}" width="32px" height="32px" id="btn_close_mypage">
          </div>
        </div>
        
        <div class="row">
          <div class="row_space_around">
            <div class="row">
              {% if request.user.profile.user_profile %}
                <img class="image_set" src="{{ request.user.profile.user_profile.url }}" width="60px" height="60px">
              {% else %}
                <img class="image_set" src="{% static 'images/logo.png' %}" width="60px" height="60px">
              {% endif %}
              <div class="column">
                <p class="color_FFF font_1">{{ request.user.profile.user_name }}</p>
                <p class="color_FFF font_2">{{ request.user.profile.user_major }}</p>
              </div>
            </div>
            <!-- update-profile address 추후 삽입 -->
            <a href="{% url 'accounts:update-profile' request.user.id %}">
              <img src="{% static 'images/edit.png' %}" width="32px" height="32px">
            </a>
          </div>
        </div>
        <div class="row_space_around">
          <a href="{% url 'users:follow-list' request.user.id %}" class="column">
            <p class="color_FFF font_3">{{ request.user.mentor_followings.count }}</p>
            <p class="color_FFF font_3">팔로잉</p>
          </a>
          <a href="{% url 'users:cibm_list' %}" class="column">
            <p class="color_FFF font_3">{{total_bm_count}}</p>
            <p class="color_FFF font_3">북마크</p>
          </a>
          <a href="{% url 'users:portfolio' request.user.id %}" class="column">
            <img src="{% static 'images/portfolio_icon.png' %}" width="32px" height="32px">
            <p class="color_FFF font_4">포트폴리오</p>
          </a>
        </div>
        <div class="btn_part">
          <a class="row_space_between round_box" href="{% url 'users:my-writing' request.user.id %}">
            <div class="row">
              <img src="{% static 'images/write_icon.png' %}" width="32px" height="32px">
              <p class="font_5 color_17">내가 쓴 글</p>
            </div>
            <img src="{% static 'images/arrow_forward.png' %}" width="32px" height="32px">
          </a>
          <a class="row_space_between round_box" href="{% url 'users:mentoring' request.user.id %}">
            <div class="row">
              <img src="{% static 'images/mentoring_icon.png' %}" width="32px" height="32px">
              <p class="font_5 color_17">멘토링 신청 현황</p>
            </div>
            <img src="{% static 'images/arrow_forward.png' %}" width="32px" height="32px">
          </a>
          <a class="row_space_between round_box" href="{% url 'users:ciapply' %}">
            <div class="row">
              <img src="{% static 'images/target_icon.png' %}" width="32px" height="32px">
              <p class="font_5 color_17">커리어 신청 현황</p>
            </div>
            <img src="{% static 'images/arrow_forward.png' %}" width="32px" height="32px">
          </a>
        </div>
      </div>
      <div class="wrapping_nav" id="wrapping_nav"></div>
    </div>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    const btn_open_mypage = document.getElementById('btn_open_mypage');
    const btn_close_mypage = document.getElementById('btn_close_mypage');
    const navbar2 = document.getElementById('navbar2');
    const wrapping_nav = document.getElementById('wrapping_nav');

    let x = false;
    wrapping_nav.style.display = "none";

    function Navbar() {
      if (x) {
        navbar2.style.animationName = 'move_navbar_up';
        wrapping_nav.style.display = "none";
      } else {
        navbar2.style.animationName = 'move_navbar_down';
        wrapping_nav.style.display = "block";
      }
      x = !x;
      navbar2.style.zIndex = x ? "10" : "2";
    }

    wrapping_nav.onclick = function () {
      navbar2.style.animationName = 'move_navbar_up';
      wrapping_nav.style.display = "none";
    }

    btn_open_mypage.onclick = Navbar;
    btn_close_mypage.onclick = Navbar;
  });

</script>