project/careers/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from main import views
from .views import *

app_name = "careers"

urlpatterns = [
    path('career-info/', career_info, name="career-info"),
    path('new-careerinfo/', new_careerinfo, name="new-careerinfo"),
    path('careerinfo-create/', careerinfo_create, name="careerinfo-create"),
    path('careerinfo-detail/<int:id>/', careerinfo_detail, name="careerinfo-detail"),
    path('careerinfo-delete/<int:id>/', careerinfo_delete, name="careerinfo-delete"),
    path('careerinfotag-careerinfos/<int:careerinfotag_id>/', careerinfotag_careerinfos, name="careerinfotag-careerinfos"),
    path('ci_bms/<int:careerinfo_id>', ci_bms, name="ci_bms"),
    path('career-program/', career_program, name="career-program"),
    path('new-careerprogram/', new_careerprogram, name="new-careerprogram"),
    path('careerprogram-create/', careerprogram_create, name="careerprogram-create"),
    path('careerprogram-detail/<int:id>/', careerprogram_detail, name="careerprogram-detail"),
    path('careerprogram-delete/<int:id>/', careerprogram_delete, name="careerprogram-delete"),
    path('careerprogramtag-careerprograms/<int:careerprogramtag_id>/', careerprogramtag_careerprograms, name="careerprogramtag-careerprograms"),
    path('cp_bms/<int:careerprogram_id>', cp_bms, name="cp_bms"),
    path('edu-info/', edu_info, name="edu-info"),
    path('new-eduinfo/', new_eduinfo, name="new-eduinfo"),
    path('eduinfo-create/', eduinfo_create, name="eduinfo-create"),
    path('eduinfo-detail/<int:id>/', eduinfo_detail, name="eduinfo-detail"),
    path('eduinfo-delete/<int:id>/', eduinfo_delete, name="eduinfo-delete"),
    path('eduinfotag-eduinfos/<int:eduinfotag_id>/', eduinfotag_eduinfos, name="eduinfotag-eduinfos"),
    path('ei_bms/<int:eduinfo_id>', ei_bms, name="ei_bms"),
    path('careerinfo-detail/<int:id>/apply/', apply_careerinfo, name="apply_careerinfo"),
    path('careerprogram-detail/<int:id>/apply/', apply_careerprogram, name="apply_careerprogram"),
    path('eduinfo-detail/<int:id>/apply/', apply_eduinfo, name="apply_eduinfo"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/main/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name = "main"
urlpatterns = [
    path('', intro, name='intro'),
    path('first-screen', first_screen, name='first-screen'),
    path('mainpage', mainpage, name='mainpage'),
    path('mentor-start', mentor_start, name='mentor-start'),
    path('mentor-list/', mentor_list, name='mentor-list'),
    path('mentor-info/<int:id>/', mentor_info, name='mentor-info'),
    path('mentor-create/', mentor_create, name='mentor-create'),
    path('mentor-enroll/', mentor_enroll, name='mentor-enroll'),
    path('mentor-relation-create/<int:id>/', mentor_relation_create, name='mentor-relation-create'),
    path('mentor-ask/<int:id>/', mentor_ask, name='mentor-ask'),
    path('create-menti/<int:id>', create_menti, name="create-menti"),
    path('follow/<int:id>/', follow, name='follow'),
    path('follow2/<int:id>/', follow2, name='follow2'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('users/', include('users.urls')),
    path('careers/', include('careers.urls')),
    path('community/', include('community.urls')),
] 

project/users/urls.py
from django.urls import path
from .views import *

app_name = "users"
urlpatterns = [
    path('mypage/<int:id>/', mypage, name="mypage"),
    path('edit_portfolio/', edit_portfolio, name='edit_portfolio'),
    path('portfolio/<int:id>', view_portfolio, name='portfolio'),
    path('follow-list/<int:id>', follow_list, name="follow-list"),
    path('bookmark/<int:id>', bookmark, name="bookmark"),
    path('my-writing/<int:id>', my_writing, name="my-writing"),
    path('mentoring/<int:id>', mentoring, name="mentoring"),
    path('career-now/<int:id>', career_now, name="career-now"),
    path('menti-list/<int:id>/', menti_list, name="menti-list"),
    path('mentoring-state/<int:id>', mentoring_state, name="mentoring-state"),
    path('cibms/', cibm_list, name="cibm_list"),
    path('cpbms/', cpbm_list, name="cpbm_list"),
    
    path('eibms/', eibm_list, name="eibm_list"),
    path('ci_bms/<int:careerinfo_id>/', ci_bms, name='ci_bms'),
    path('cp_bms/<int:careerprogram_id>/', cp_bms, name='cp_bms'),
    path('ei_bms/<int:eduinfo_id>/', ei_bms, name='ei_bms'),
    path('ciapply/', ciapply, name="ciapply"),
    path('cpapply/', cpapply, name="cpapply"),
    path('eiapply/', eiapply, name="eiapply"),
]

project/careers/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.contrib import messages
from django.db.models import Q
from .models import Careerinfo, Careerinfotag, Careerprogram, Careerprogramtag, Eduinfo, Eduinfotag, Ciapply, Cpapply, Eiapply
from django.db.models import Sum
def career_info(request):
    order = request.GET.get('order', 'latest')
    search_query = request.GET.get('search', '')
    if search_query.startswith('#'):
        tag_name = search_query[1:]
        careerinfos = Careerinfo.objects.filter(
            Q(careerinfotags__name__icontains=tag_name)
        ).distinct()
    else:
        careerinfos = Careerinfo.objects.filter(
            Q(title__icontains=search_query) |
            Q(company__icontains=search_query) |
            Q(field__icontains=search_query) |
            Q(content__icontains=search_query)
        ).distinct()

    if order == 'latest':
        careerinfos = careerinfos.order_by('-pub_date')
    elif order == 'oldest':
        careerinfos = careerinfos.order_by('pub_date')

    total_careerinfo_count = careerinfos.count()
    return render(request, 'careers/career-info.html', {
        'careerinfos': careerinfos,
        'total_careerinfo_count': total_careerinfo_count,
        'selected_order': order,
        'search_query': search_query,
    })

def career_program(request):
    order = request.GET.get('order', 'latest')
    search_query = request.GET.get('search', '')
    if search_query.startswith('#'):
        tag_name = search_query[1:]
        careerprograms = Careerprogram.objects.filter(
            Q(careerprogramtags__name__icontains=tag_name)
        ).distinct()
    else:
        careerprograms = Careerprogram.objects.filter(
            Q(title__icontains=search_query) |
            Q(place__icontains=search_query) |
            Q(field__icontains=search_query) |
            Q(content__icontains=search_query)
        ).distinct()

    if order == 'latest':
        careerprograms = careerprograms.order_by('-pub_date')
    elif order == 'oldest':
        careerprograms = careerprograms.order_by('pub_date')

    total_careerprogram_count = careerprograms.count()
    return render(request, 'careers/career-program.html', {
        'careerprograms': careerprograms,
        'total_careerprogram_count': total_careerprogram_count,
        'selected_order': order,
        'search_query': search_query,
    })

def edu_info(request):
    order = request.GET.get('order', 'latest')
    search_query = request.GET.get('search', '')
    if search_query.startswith('#'):
        tag_name = search_query[1:]
        eduinfos = Eduinfo.objects.filter(
            Q(eduinfotags__name__icontains=tag_name)
        ).distinct()
    else:
        eduinfos = Eduinfo.objects.filter(
            Q(title__icontains=search_query) |
            Q(place__icontains=search_query) |
            Q(field__icontains=search_query) |
            Q(content__icontains=search_query)
        ).distinct()

    if order == 'latest':
        eduinfos = eduinfos.order_by('-pub_date')
    elif order == 'oldest':
        eduinfos = eduinfos.order_by('pub_date')

    total_eduinfo_count = eduinfos.count()
    return render(request, 'careers/edu-info.html', {
        'eduinfos': eduinfos,
        'total_eduinfo_count': total_eduinfo_count,
        'selected_order': order,
        'search_query': search_query,
    })

def careerinfo_create(request):
    if request.method == "POST":
        # 디버그 출력문 추가
        print(request.POST)

        new_careerinfo = Careerinfo()

        new_careerinfo.title = request.POST.get('title')
        new_careerinfo.writer = request.user
        new_careerinfo.company = request.POST.get('company')
        new_careerinfo.field = request.POST.get('field')
        new_careerinfo.content = request.POST.get('content')
        new_careerinfo.startline = request.POST.get('startline')
        new_careerinfo.deadline = request.POST.get('deadline')
        new_careerinfo.pub_date = timezone.now()
        new_careerinfo.image = request.FILES.get('image')
        
        new_careerinfo.save()

        careerinfotags = request.POST.get('careerinfotags', '')
        tag_names = [tag.strip() for tag in careerinfotags.split('#') if tag.strip()]
        
        careerinfotag_list = []
        for tag_name in tag_names:
            careerinfotag, created = Careerinfotag.objects.get_or_create(name=tag_name)
            careerinfotag_list.append(careerinfotag)

        new_careerinfo.careerinfotags.set(careerinfotag_list)

        return redirect('careers:careerinfo-detail', new_careerinfo.id)

    return render(request, 'careers/new-careerinfo.html')

def careerprogram_create(request):
    if request.method == "POST":
        # 디버그 출력문 추가
        print(request.POST)

        new_careerprogram = Careerprogram()

        new_careerprogram.title = request.POST.get('title')
        new_careerprogram.writer = request.user
        new_careerprogram.place = request.POST.get('place')
        new_careerprogram.field = request.POST.get('field')
        new_careerprogram.content = request.POST.get('content')
        new_careerprogram.startline = request.POST.get('startline')
        new_careerprogram.deadline = request.POST.get('deadline')
        new_careerprogram.pub_date = timezone.now()
        new_careerprogram.image = request.FILES.get('image')
        
        new_careerprogram.save()

        careerprogramtags = request.POST.get('careerprogramtags', '')
        tag_names = [tag.strip() for tag in careerprogramtags.split('#') if tag.strip()]
        
        careerprogramtag_list = []
        for tag_name in tag_names:
            careerprogramtag, created = careerprogramtag.objects.get_or_create(name=tag_name)
            careerprogramtag_list.append(careerprogramtag)

        new_careerprogram.careerprogramtags.set(careerprogramtag_list)

        return redirect('careers:careerprogram-detail', new_careerprogram.id)

    return render(request, 'careers/new-careerprogram.html')

def eduinfo_create(request):
    if request.method == "POST":
        new_eduinfo = Eduinfo()
        
        new_eduinfo.title = request.POST.get('title')
        new_eduinfo.writer = request.user
        new_eduinfo.place = request.POST.get('place')
        new_eduinfo.field = request.POST.get('field')
        new_eduinfo.content = request.POST.get('content')
        new_eduinfo.startline = request.POST.get('startline')
        new_eduinfo.deadline = request.POST.get('deadline')
        new_eduinfo.pub_date = timezone.now()
        new_eduinfo.image = request.FILES.get('image')
        
        new_eduinfo.save()

        eduinfotags = request.POST.get('eduinfotags', '')
        tag_names = [tag.strip() for tag in eduinfotags.split('#') if tag.strip()]
        
        eduinfotag_list = []
        for tag_name in tag_names:
            eduinfotag, created = Eduinfotag.objects.get_or_create(name=tag_name)
            eduinfotag_list.append(eduinfotag)

        new_eduinfo.eduinfotags.set(eduinfotag_list)

        return redirect('careers:eduinfo-detail', new_eduinfo.id)

    return render(request, 'careers/new-eduinfo.html')


def new_careerinfo(request):
    return render(request, 'careers/new-careerinfo.html')

def new_careerprogram(request):
    return render(request, 'careers/new-careerprogram.html')

def new_eduinfo(request):
    return render(request, 'careers/new-eduinfo.html')

def careerinfo_detail(request, id):
    careerinfo = get_object_or_404(Careerinfo, pk=id)
    user = request.user
    has_applied = Ciapply.objects.filter(user=user, careerinfo=careerinfo).exists()
    return render(request, 'careers/careerinfo-detail.html', {
        'careerinfo': careerinfo,
        'has_applied': has_applied
    })

def careerprogram_detail(request, id):
    careerprogram = get_object_or_404(Careerprogram, pk=id)
    user = request.user
    has_applied = Cpapply.objects.filter(user=user, careerprogram=careerprogram).exists()
    return render(request, 'careers/careerprogram-detail.html', {
        'careerprogram': careerprogram,
        'has_applied': has_applied
    })

def eduinfo_detail(request, id):
    eduinfo = get_object_or_404(Eduinfo, pk=id)
    user = request.user
    has_applied = Eiapply.objects.filter(user=user, eduinfo=eduinfo).exists()
    return render(request, 'careers/eduinfo-detail.html', {
        'eduinfo': eduinfo,
        'has_applied': has_applied
    })


def careerinfo_delete(request, id):
    delete_careerinfo = Careerinfo.objects.get(pk=id)
    delete_careerinfo.delete()
    return redirect('careers:career-info')

def careerprogram_delete(request, id):
    delete_careerprogram_ = Careerprogram.objects.get(pk=id)
    delete_careerprogram_.delete()
    return redirect('careers:career-program')

def eduinfo_delete(request, id):
    delete_eduinfo = Eduinfo.objects.get(pk=id)
    delete_eduinfo.delete()
    return redirect('careers:edu-info')

def careerinfotag_careerinfos(request, careerinfotag_id):
    careerinfotag = get_object_or_404(Careerinfotag, id=careerinfotag_id)
    careerinfos = careerinfotag.careerinfos.all()
    return render(request, 'careers/careerinfotag-careerinfo.html', {
        'careerinfotag' : careerinfotag,
        'careerinfos' : careerinfos
    })

def careerprogramtag_careerprograms(request, careerprogramtag_id):
    careerprogramtag = get_object_or_404(Careerprogramtag, id=careerprogramtag_id)
    careerprograms = careerprogramtag.careerprograms.all()
    return render(request, 'careers/careerprogramtag-careerprogram.html', {
        'careerprogramtag' : careerprogramtag,
        'careerprograms' : careerprograms
    })

def eduinfotag_eduinfos(request, eduinfotag_id):
    eduinfotag = get_object_or_404(Eduinfotag, id=eduinfotag_id)
    eduinfos = eduinfotag.eduinfos.all()
    return render(request, 'careers/eduinfotag-eduinfo.html', {
        'eduinfotag' : eduinfotag,
        'eduinfos' : eduinfos
    })

project/careers/templates/careers/careerinfo-detail.html
{% extends 'base_with_nav.html' %} {% load static %} {% block content %}

<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/careers/careerinfo_detail.css'%}"
/>

<div class="screen">
	<div class="main">
    <div class="body">
			<div class="nav">
				<div class="left" style="z-index: 1;">
					<a href="{% url 'careers:career-info' %}">
            <img src="{% static 'images/arrow-24.png' %}" width='32px' height='32px'>
					</a>
				</div>
				<div><p class="color_28 title_text" style="text-align: center;">커리어</p></div>
				<div style="width: 32px;"></div>
			</div>
      <p class="color_black title_text2" style="padding-top: 16px;">{{ careerinfo.title }}</p>
      <div class="box">
        <div class="column" style="gap: 16px;">
          {% if careerinfo.image %}
            <img src="{{ careerinfo.image.url }}" alt="사진" width="100%">
          {% else %}
            <img src="{% static 'images/calendar.png' %}" alt="사진" width="100%">
          {% endif %}
          <div class="text_board">
            <div class="row1">
              <div class="row_100">
                <img src="{% static 'images/calendar.png' %}" width="20px" height="20px">
                <p class="text4 color_17">지원일</p>
              </div>
              <p class="text5 color_61">{{careerinfo.startline}} - {{careerinfo.deadline}}</p>
              <form action="{% url 'careers:ci_bms' careerinfo.id %}" method="post">
                {% csrf_token %}
                {% if user in careerinfo.ci_bm.all %}
                  <button type="submit"><img src="{% static 'images/filled_bookmark.png' %}" width="20px" height="20px"></button>
                {% else %}
                  <button type="submit"><img src="{% static 'images/unfilled_bookmark.png' %}" width="20px" height="20px"></button>
                {% endif %}
              </form>
            </div>
            <div class="row1">
              <div class="row_100">
                <img src="{% static 'images/location.png' %}" width="20px" height="20px">
                <p class="text4 color_17 length_limit">기업명</p>
              </div>
              <p class="text5 color_61" style="width: 200px;">{{careerinfo.company}}</p>
              <div style="width: 20px;"></div>
            </div>
            <div class="row1">
              <div class="row_100">
                <img src="{% static 'images/book.png' %}" width="20px" height="20px">
                <p class="text4 color_17">분야</p>
              </div>
              <p class="text5 color_61" style="width: 200px;">{{careerinfo.field}}</p>
              <div style="width: 20px;"></div>
            </div>
            <hr style="width: 100%;">
            <div class="context">
              <p class="color_17 context_text">내용</p>
              <p class="color_61 context_text2">{{careerinfo.content}}</p>
            </div>
            <div style="width: 20px;"></div>
          </div>
        </div>
        {% for careerinfotag in careerinfo.careerinfotags.all %}
          <a href="{% url 'careers:careerinfotag-careerinfos' careerinfotag.id %}">#{{ careerinfotag.name }} </a>
        {% endfor %}
      </div>
      {% if not has_applied %}
        <form id="form_app" style="display: flex; justify-content: center;" method="post" action="{% url 'careers:apply_careerinfo' careerinfo.id %}">
          {% csrf_token %}
          <button style="margin-top: 20px;" class="btn_ask color_FF" type="button" id="btn_app">지원하기</button>
        </form>
      {% else %}
        <form id="form_noapp" style="display: flex; justify-content: center;" method="post" action="{% url 'careers:apply_careerinfo' careerinfo.id %}">
          {% csrf_token %}
          <button style="margin-top: 20px;"  class="btn_ask2 color_FF" type="button" id="btn_noapp">지원취소</button>
        </form>
      {% endif %}

      {% if careerinfo.writer == user %}
        <a class="btn_ask2" style="width: 286px;" href="{% url 'careers:careerinfo-delete' careerinfo.id %}">삭제하기</a>
      {% endif %}
		</div>
	</div>
  <div class="wrapping" id="wrapping"></div>
  <div class="wrapping" id="wrapping2"></div>
  <div class="toast" id="toast" style="align-items: center;">
    <img src="{% static 'images/complete.png' %}" width="90px" height="90px">
    <p class="color_28 title_text2">지원이 완료되었습니다.</p>
    <p class="color_9D title_text3">커리어 신청 현황 화면으로 화면이 전환됩니다.</p>
  </div>
  <div class="toast" id="toast2" style="align-items: center;">
    <img src="{% static 'images/complete_red.png' %}" width="90px" height="90px">
    <p class="color_28 title_text2">지원이 취소되었습니다.</p>
    <p class="color_9D title_text3">커리어 신청 현황 화면으로 화면이 전환됩니다.</p>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    const toast = document.getElementById("toast");
    const toast2 = document.getElementById("toast2");

    const wrapping = document.getElementById("wrapping");
    const wrapping2 = document.getElementById("wrapping2");

    const btn_app = document.getElementById("btn_app");
    const btn_noapp = document.getElementById("btn_noapp");

    const form_app = document.getElementById("form_app");
    const form_noapp = document.getElementById("form_noapp");

    wrapping.style.display = "none";
    wrapping2.style.display = "none";
    toast.style.display = "none";
    toast2.style.display = "none";

    if (btn_app) {
      btn_app.onclick = function () {
        wrapping2.style.display = "block";
        toast.style.display = "";
        setTimeout(function() {
          form_app.submit();
        }, 1500);
      };
    }

    if (btn_noapp) {
      btn_noapp.onclick = function () {
        wrapping2.style.display = "block";
        toast2.style.display = "";
        setTimeout(function() {
          form_noapp.submit();
        }, 1500);
      };
    }

  });
  
</script>



{% endblock %}

<!-- <h3>{{careerinfo.title}}</h3>
지원일 : {{careerinfo.startline}} - {{careerinfo.deadline}}
기업명 : {{careerinfo.company}}
분야: {{careerinfo.field}} -->
<!-- <p>
    {% for careerinfotag in careerinfo.careerinfotags.all %}
        <a href="{% url 'careers:careerinfotag-careerinfos' careerinfotag.id %}">#{{ careerinfotag.name }} </a>
    {% endfor %}
</p>
<hr/> -->

<!-- <form action="{% url 'careers:ci_bms' careerinfo.id %}" method="post">
    {% csrf_token %}
    {% if user in careerinfo.ci_bm.all %}
        <button type="submit">북마크 취소</button>
    {% else %}
        <button type="submit">북마크 추가</button>
    {% endif %}
    </form>

{{careerinfo.cibm_count}}개
{% if careerinfo.image %}
    <p><img src="{{ careerinfo.image.url }}" alt="사진" width="100px"></p>
{% endif %}

<p>{{careerinfo.content}}</p>
{% if careerinfo.writer == user %}
<a href="{% url 'careers:careerinfo-delete' careerinfo.id %}">삭제하기</a>
{% endif %}
<br> -->

project/careers/templates/careers/careerprogram-detail.html
{% extends 'base_with_nav.html' %} {% load static %} {% block content %}

<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/careers/careerprogram_detail.css'%}"
/>

<div class="screen">
	<div class="main">
    <div class="body">
			<div class="nav">
				<div class="left" style="z-index: 1;">
					<a href="{% url 'careers:career-program' %}">
            <img src="{% static 'images/arrow-24.png' %}" width='32px' height='32px'>
					</a>
				</div>
				<div><p class="color_28 title_text" style="text-align: center;">커리어</p></div>
				<div style="width: 32px;"></div>
			</div>
      <p class="color_black title_text2" style="padding-top: 16px;">{{ careerprogram.title }}</p>
      <div class="box">
        <div class="column" style="gap: 16px;">
          {% if careerprogram.image %}
            <img src="{{ careerprogram.image.url }}" alt="사진" width="100%">
          {% else %}
            <img src="{% static 'images/calendar.png' %}" alt="사진" width="100%">
          {% endif %}
          <div class="text_board">
            <div class="row1">
              <div class="row_100">
                <img src="{% static 'images/calendar.png' %}" width="20px" height="20px">
                <p class="text4 color_17">지원일</p>
              </div>
              <p class="text5 color_61">{{careerprogram.startline}} - {{careerprogram.deadline}}</p>
              <form action="{% url 'careers:cp_bms' careerprogram.id %}" method="post">
                {% csrf_token %}
                {% if user in careerprogram.cp_bm.all %}
                    <button type="submit"><img src="{% static 'images/filled_bookmark.png' %}" width="20px" height="20px"></button>
                {% else %}
                    <button type="submit"><img src="{% static 'images/unfilled_bookmark.png' %}" width="20px" height="20px"></button>
                {% endif %}
              </form>
            </div>
            <div class="row1">
              <div class="row_100">
                <img src="{% static 'images/location.png' %}" width="20px" height="20px">
                <p class="text4 color_17">장소</p>
              </div>
              <p class="text5 color_61 length_limit" style="width: 200px;">{{careerprogram.place}}</p>
              <div style="width: 20px;"></div>
            </div>
            <div class="row1">
              <div class="row_100">
                <img src="{% static 'images/book.png' %}" width="20px" height="20px">
                <p class="text4 color_17">분야</p>
              </div>
              <p class="text5 color_61" style="width: 200px;">{{careerprogram.field}}</p>
              <div style="width: 20px;"></div>
            </div>
            <hr style="width: 100%;">
            <div class="context">
              <p class="color_17 context_text">내용</p>
              <p class="color61 context_text2">{{careerprogram.content}}</p>
            </div>
            <div style="width: 20px;"></div>
          </div>
        </div>
        {% for careerprogramtag in careerprogram.careerprogramtags.all %}
          <a href="{% url 'careers:careerprogramtag-careerprograms' careerprogramtag.id %}">#{{ careerprogramtag.name }} </a>
        {% endfor %}
      </div>
      {% if not has_applied %}
      <form id="form_app" style="display: flex; justify-content: center;" method="post" action="{% url 'careers:apply_careerprogram' careerprogram.id %}">
            {% csrf_token %}
            <button style="margin-top: 20px;" class="btn_ask color_FF" type="button" id="btn_app">지원하기</button>
        </form>
      {% else %}
      <form id="form_noapp" style="display: flex; justify-content: center;" method="post" action="{% url 'careers:apply_careerprogram' careerprogram.id %}">
            {% csrf_token %}
            <button style="margin-top: 20px;" class="btn_ask2 color_FF" type="button" id="btn_noapp">지원취소</button>
        </form>
      {% endif %}

      {% if careerprogram.writer == user %}
        <a class="btn_ask2" style="width: 286px;" href="{% url 'careers:careerprogram-delete' careerprogram.id %}">삭제하기</a>
      {% endif %}
		</div>
	</div>
  <div class="wrapping" id="wrapping"></div>
  <div class="wrapping" id="wrapping2"></div>
  <div class="toast" id="toast" style="align-items: center;">
    <img src="{% static 'images/complete.png' %}" width="90px" height="90px">
    <p class="color_28 title_text2">지원이 완료되었습니다.</p>
    <p class="color_9D title_text3">커리어 신청 현황 화면으로 화면이 전환됩니다.</p>
  </div>
  <div class="toast" id="toast2" style="align-items: center;">
    <img src="{% static 'images/complete_red.png' %}" width="90px" height="90px">
    <p class="color_28 title_text2">지원이 취소되었습니다.</p>
    <p class="color_9D title_text3">커리어 신청 현황 화면으로 화면이 전환됩니다.</p>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    const toast = document.getElementById("toast");
    const toast2 = document.getElementById("toast2");

    const wrapping = document.getElementById("wrapping");
    const wrapping2 = document.getElementById("wrapping2");

    const btn_app = document.getElementById("btn_app");
    const btn_noapp = document.getElementById("btn_noapp");

    const form_app = document.getElementById("form_app");
    const form_noapp = document.getElementById("form_noapp");

    wrapping.style.display = "none";
    wrapping2.style.display = "none";
    toast.style.display = "none";
    toast2.style.display = "none";

    if (btn_app) {
      btn_app.onclick = function () {
        wrapping2.style.display = "block";
        toast.style.display = "";
        setTimeout(function() {
          form_app.submit();
        }, 700);
      };
    }

    if (btn_noapp) {
      btn_noapp.onclick = function () {
        wrapping2.style.display = "block";
        toast2.style.display = "";
        setTimeout(function() {
          form_noapp.submit();
        }, 700);
      };
    }

  });
</script>



{% endblock %}

project/careers/templates/careers/new-info.html
{% if info.id %}
    <form action="{% url 'careers:create' info.id %}" method="post">
{% else %}
    <form action="{% url 'careers:create' %}" method="post">
{% endif %}
    {% csrf_token %}
    <p>제목 : <input type="text" name="title"></p>
    <p>작성자 : <input type="text" name="writer"></p>
    <p>지역 : <input type="text" name="location"></p>
    <p>내용 : <textarea type="text" name="body" id="" cols="30" rows="10"></textarea></p>
    <button type="submit">제출</button>
    <h1>메인 페이지</h1>
    <a href="{% url 'users:mypage' id=request.user.id %}">내 마이페이지로 이동</a>
</form>