project/accounts/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name = "accounts"
urlpatterns = [
    path('login/', login, name="login"),
    path('logout/', logout, name="logout"),
    path('signup/', signup, name="signup"),
    path('signup2/', signup2, name="signup2"),
    path('signup3/', signup3, name="signup3"),
    path('update-profile/<int:id>', update_profile, name="update-profile"),
    path('finishjoin/', finishjoin, name="finishjoin"),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/careers/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from main import views
from .views import *

app_name = "careers"

urlpatterns = [
    path('career-info/', career_info, name="career-info"),
    path('new-careerinfo/', new_careerinfo, name="new-careerinfo"),
    path('careerinfo-create/', careerinfo_create, name="careerinfo-create"),
    path('careerinfo-detail/<int:id>/', careerinfo_detail, name="careerinfo-detail"),
    path('careerinfo-delete/<int:id>/', careerinfo_delete, name="careerinfo-delete"),
    path('careerinfotag-careerinfos/<int:careerinfotag_id>/', careerinfotag_careerinfos, name="careerinfotag-careerinfos"),
    path('ci_bms/<int:careerinfo_id>', ci_bms, name="ci_bms"),
    path('career-program/', career_program, name="career-program"),
    path('new-careerprogram/', new_careerprogram, name="new-careerprogram"),
    path('careerprogram-create/', careerprogram_create, name="careerprogram-create"),
    path('careerprogram-detail/<int:id>/', careerprogram_detail, name="careerprogram-detail"),
    path('careerprogram-delete/<int:id>/', careerprogram_delete, name="careerprogram-delete"),
    path('careerprogramtag-careerprograms/<int:careerprogramtag_id>/', careerprogramtag_careerprograms, name="careerprogramtag-careerprograms"),
    path('cp_bms/<int:careerprogram_id>', cp_bms, name="cp_bms"),
    path('edu-info/', edu_info, name="edu-info"),
    path('new-eduinfo/', new_eduinfo, name="new-eduinfo"),
    path('eduinfo-create/', eduinfo_create, name="eduinfo-create"),
    path('eduinfo-detail/<int:id>/', eduinfo_detail, name="eduinfo-detail"),
    path('eduinfo-delete/<int:id>/', eduinfo_delete, name="eduinfo-delete"),
    path('eduinfotag-eduinfos/<int:eduinfotag_id>/', eduinfotag_eduinfos, name="eduinfotag-eduinfos"),
    path('ei_bms/<int:eduinfo_id>', ei_bms, name="ei_bms"),
    path('careerinfo-detail/<int:id>/apply/', apply_careerinfo, name="apply_careerinfo"),
    path('careerprogram-detail/<int:id>/apply/', apply_careerprogram, name="apply_careerprogram"),
    path('eduinfo-detail/<int:id>/apply/', apply_eduinfo, name="apply_eduinfo"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/community/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name = "community"
urlpatterns = [
    path('free-board/', free_board, name='free-board'),
    path('move-board/', move_board, name='move-board'),
    path('new-free/', new_free, name="new-free"),
    path('free-create/', free_create, name="free-create"),
    path('free-detail/<int:id>/', free_detail, name='free-detail'),
    path('free-edit/<int:id>/', free_edit, name="free-edit"),
    path('free-update/<int:id>/', free_update, name="free-update"),
    path('free-delete/<int:id>/', free_delete, name="free-delete"),
    path('new-move/', new_move, name="new-move"),
    path('move-create/', move_create, name="move-create"),
    path('move-detail/<int:id>/', move_detail, name='move-detail'),
    path('move-edit/<int:id>/', move_edit, name="move-edit"),
    path('move-update/<int:id>/', move_update, name="move-update"),
    path('move-delete/<int:id>/', move_delete, name="move-delete"),
    path('freetag-list', freetag_list, name="freetag-list"),
    path('movetag-list', movetag_list, name="movetag-list"),
    path('freetag-frees/<int:freetag_id>', freetag_frees, name="freetag-frees"),
    path('movetag-moves/<int:movetag_id>', movetag_moves, name="movetag-moves"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/main/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name = "main"
urlpatterns = [
    path('', intro, name='intro'),
    path('first-screen', first_screen, name='first-screen'),
    path('mainpage', mainpage, name='mainpage'),
    path('mentor-start', mentor_start, name='mentor-start'),
    path('mentor-list/', mentor_list, name='mentor-list'),
    path('mentor-info/<int:id>/', mentor_info, name='mentor-info'),
    path('mentor-create/', mentor_create, name='mentor-create'),
    path('mentor-enroll/', mentor_enroll, name='mentor-enroll'),
    path('mentor-relation-create/<int:id>/', mentor_relation_create, name='mentor-relation-create'),
    path('mentor-ask/<int:id>/', mentor_ask, name='mentor-ask'),
    path('create-menti/<int:id>', create_menti, name="create-menti"),
    path('follow/<int:id>/', follow, name='follow'),
    path('follow2/<int:id>/', follow2, name='follow2'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('users/', include('users.urls')),
    path('careers/', include('careers.urls')),
    path('community/', include('community.urls')),
] 

project/main/models.py
from django.db import models
from django.contrib.auth.models import User
from accounts.models import Profile
from django.dispatch import receiver
from django.db.models.signals import post_save

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=30, null=True, blank=True)
    def __str__(self):
        return self.name

class Mentor(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    mentor_company = models.CharField(max_length=50)
    mentor_dept = models.CharField(max_length=50)
    mentor_work = models.CharField(max_length=50)
    
    mentor_summary = models.CharField(max_length=50)
    mentor_info = models.TextField(max_length=300)
    mentor_career = models.CharField(max_length=50)

    mentor_certificate = models.CharField(max_length=100, null=True, blank=True)
    mentor_id_card = models.ImageField(upload_to="mentor_1/")
    mentor_name_card = models.ImageField(upload_to="mentor_2/")

    # follow = models.ManyToManyField(User, related_name='follow', blank=True)
    # follow_count = models.PositiveIntegerField(default=0)
    
    mentor_at = models.DateTimeField()
    followers = models.ManyToManyField(User, related_name='mentor_followings', blank=True)

    categories = models.ManyToManyField(Category, related_name='mentors', blank=True)
    mentor_ship = models.ManyToManyField(User, related_name='menti_ship', symmetrical=False, blank=True)
    def __str__(self):
        return self.user

class Menti(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    mentor = models.ForeignKey(Mentor, on_delete=models.CASCADE)
    summary = models.CharField(max_length=50)
    content = models.CharField(max_length=500)
    state = models.CharField(max_length=30, null=True, blank=True)
    mentoring_at = models.DateField(blank=True, null=True)

class Relation_mentor(models.Model):
    mentor = models.ForeignKey(Mentor, on_delete=models.CASCADE)
    menti = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.menti

project/main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from .models import Mentor, Category, Relation_mentor, Menti
from django.contrib.auth.models import User
from community.models import Free, Move


def intro(request):
    return render(request, 'main/intro.html')

def first_screen(request):
    return render(request, 'main/first_screen.html')

def mainpage(request):
    user = User.objects.all()
    mentor = Mentor.objects.all()
    relation = Menti.objects.all()
    free = Free.objects.all()
    move = Move.objects.all()
    board = free.count() + move.count()

    content = {
        'user':user,
        'mentor':mentor,
        'relation':relation,
        'board':board,
    }
    return render(request, 'main/mainpage.html', content)

def mentor_start(request):
    return render(request, 'main/mentor_start.html')

def mentor_list(request):
    category_list = [
            '인사/노무',
            'IT개발/데이터',
            '디자인',
            '영상/판매/무역',
            '상품기획/MD',
            '서비스',
            '생산',
            '의료',
            '건설/건축',
            '연구/R&D',
            '교육',
            '금융/보험',
            '미디어/스포츠',
            '교육'
        ]
    if request.method == 'POST':
        selected_categories = request.POST.getlist('categories')
        if selected_categories:
            selected_category_names = [category_list[int(i)] for i in selected_categories]
            mentors = Mentor.objects.filter(mentor_work__in=selected_category_names)
            mentors = mentors.order_by('-mentor_at')
            return render(request, 'main/mentor_list.html', {'mentors': mentors})
        else:
            mentors = Mentor.objects.all()
            mentors = mentors.order_by('-mentor_at')
            return render(request, 'main/mentor_list.html', {'mentors': mentors})
    else:
        mentors = Mentor.objects.all()
        mentors = mentors.order_by('-mentor_at')
    return render(request, 'main/mentor_list.html', {'mentors': mentors})

def mentor_enroll(request):
    return render(request, 'main/mentor_enroll.html')

def mentor_create(request):
    if request.user.is_authenticated:
        new_mentor = Mentor()
        new_mentor.user = request.user
        new_mentor.mentor_company = request.POST['mentor_company']
        new_mentor.mentor_dept = request.POST['mentor_dept']
        new_mentor.mentor_work = request.POST['mentor_work']
        new_mentor.mentor_summary = request.POST['mentor_summary']
        new_mentor.mentor_info = request.POST['mentor_info']
        new_mentor.mentor_career = request.POST['mentor_career']
        new_mentor.mentor_certificate = request.POST['mentor_certificate']
        new_mentor.mentor_id_card = request.FILES.get('image_1')
        new_mentor.mentor_name_card = request.FILES.get('image_2')
        new_mentor.mentor_at = timezone.now()

        new_mentor.save()
        return redirect('main:mentor-list')
    else:
        return redirect('main:first-screen')

def mentor_info(request, id):
    mentor = get_object_or_404(Mentor, pk = id)
    return render(request, 'main/mentor_info.html', {'mentor' : mentor})

def mentor_relation_create(request, id):
    user=request.user
    mentor = get_object_or_404(Mentor, pk=id)
    new_relation = Relation_mentor()
    new_relation.mentor = mentor
    new_relation.menti = user
    new_relation.save()

    return redirect('users:mentoring', request.user.id)

def mentor_ask(request, id):
    user = request.user
    mentor = get_object_or_404(Mentor, pk = id)
    menti = Menti.objects.all()
    is_mentoring = user in mentor.mentor_ship.all()
    if mentor.user == request.user:
        return redirect('main:mentor-list')
    else:
        if is_mentoring:
            mentor.mentor_ship.remove(user)
            menti.delete()
            return redirect('main:mentor-info', mentor.id)
        else:
            return render(request, 'main/mentor_ask.html', {'mentor':mentor})

def create_menti(request, id):
    user = request.user
    mentor = get_object_or_404(Mentor, pk=id)
    new_menti = Menti()
    new_menti.user = user
    new_menti.mentor = mentor
    new_menti.summary = request.POST['summary']
    new_menti.content = request.POST['content']
    new_menti.state = ''
    new_menti.mentoring_at = timezone.now()
    new_menti.save()
    mentor.mentor_ship.add(user)
    return redirect('main:mentor-relation-create', mentor.id)

def follow(request, id):
    user = request.user
    mentor = get_object_or_404(Mentor, pk=id)
    is_follower = user in mentor.followers.all()
    if is_follower:
        mentor.followers.remove(user)
    else:
        mentor.followers.add(user)
    return redirect('main:mentor-info', mentor.id)

def follow2(request, id):
    user = request.user
    mentor = get_object_or_404(Mentor, pk=id)
    is_follower = user in mentor.followers.all()
    if is_follower:
        mentor.followers.remove(user)
    else:
        mentor.followers.add(user)
    return redirect('users:follow-list', user.id)

project/main/templates/main/mainpage.html
{% extends 'base_with_nav.html' %} 
{% block content %} 
{% load static %}
<link 
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/main/mainpage.css'%}"
/>

<div class="screen">
  <div class="main">
    <div class="body">
      <div class="small_nav">
        <div class="left">
        </div>
        <h2 class='main_text_ho color_1E'>CEHAT KEY</h2>
        <div class="right">
        </div>
      </div>
      <div class="btn_list">
        <a href="{% url 'main:mentor-start' %}" class="btn_rec" id="btn_rec">
          <img src="{% static 'images/멘토바.png' %}" width='260px' height='210px' id="img_rec">
          <p class="text_set1 font_VIT color_F">멘토</p>
          <p class="text_set2 font_21 color_28">동문선배가 다 모였다<br>멘토링 매칭하기</p>
        </a>
        <div class="btn_rho" id="btn_rho">
          <img src="{% static 'images/커뮤니티.png' %}" width='160px' height='155px' id="img_rho">
          <a href="{% url 'community:free-board' %}" class="box_set2">
            <p class="text_set3 font_VIT_2 color_F">커뮤니티</p>
            <p class="text_set4 font_21 color_28">자유게시판<br>이직게시판</p>
          </a>
        </div>
        <div class="btn_cir" id="btn_cir">
          <img src="{% static 'images/커리어.png' %}" width='350px' height='110px' id="img_cir">
          <a href="{% url 'careers:career-info' %}" class="box_set3">
            <p class="text_set5 font_CORE color_F">커리어</p>
            <p class="text_set6 font_21 color_28">채용, 취업, 교육<br>프로그램</p>
          </a>
        </div>
      </div>
      <div class="text_dongguk">
        <p class="text_sub">벌써 많은 동국인이</p>
        <div style="display: flex; flex-direction: row;">
          <p class="text_point">취트키</p><p class="text_sub">와 함께하고 있어요!</p>
        </div>
      </div>
      <div class="signup_list"> 
        <div class='membermentor'>
          <div class="signup_detail">
            <img src="{% static 'images/signup1.png' %}" width="120px" height='120px'>
            <p class="content">가입한 취트키 멤버</p>
            <p class="count" id="userCount">{{ user.count }}</p>
          </div>
          <div class="signup_detail">
            <img src="{% static 'images/signup3.png' %}" width="120px" height='120px'>
            <p class="content">작성된 게시글</p>
            <p class="count" id="boardCount">{{ board }}</p>
          </div>
        </div>
        <div class='membermentor2'>
          <div class="signup_detail">
            <img src="{% static 'images/signup2.png' %}" width="120px" height='120px'>
            <p class="content">이루어진 멘토링</p>
            <p class="count" id="relationCount">{{ relation.count }}</p>
          </div>
          <div class="signup_detail">
            <img src="{% static 'images/signup4.png' %}" width="120px" height='120px'>
            <p class="content">등록된 멘토</p>
            <p class="count" id="mentorCount">{{ mentor.count }}</p>
          </div>
        </div>
      </div>
      <div class="credit">
        <div class="webname">
          <p class="webname_bold">CHEAT KEY</p>
          <p class="font_400">취트키 CHEAT KEY</p>
        </div>
        <div class="maker">
          <p class="font_500">Product Designer | 구도욱<br>Front End | 오태준, 최민<br>Back End | 박선우, 황채현</p>
        </div>
        <div class="instayoutube_icon"></div>
        <div class="copyright font_200">Copyright ⓒ 2024 심바오 Team. All Rights Reserved.</div>
      </div>
    </div>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    const btnRec = document.getElementById("btn_rec");
    const imgRec = document.getElementById("img_rec");
    const btnRho = document.getElementById("btn_rho");
    const imgRho = document.getElementById("img_rho");
    const btnCir = document.getElementById("btn_cir");
    const imgCir = document.getElementById("img_cir");

    btnRec.addEventListener("mousedown", function() {
      imgRec.src = "{% static 'images/멘토바누를때.png' %}";
    });

    btnRec.addEventListener("mouseup", function() {
      setTimeout(() => {
        imgRec.src = "{% static 'images/멘토바.png' %}";
      }, 300);
    });

    btnRho.addEventListener("mousedown", function() {
      imgRho.src = "{% static 'images/커뮤니티누를때.png' %}";
    });

    btnRho.addEventListener("mouseup", function() {
      setTimeout(() => {
        imgRho.src = "{% static 'images/커뮤니티.png' %}";
      }, 300);
    });

    btnCir.addEventListener("mousedown", function() {
      imgCir.src = "{% static 'images/커리어누를때.png' %}";
    });

    btnCir.addEventListener("mouseup", function() {
      setTimeout(() => {
        imgCir.src = "{% static 'images/커리어.png' %}";
      }, 300);
    });

    function animateCounts() {
      const userCount = parseInt("{{ user.count }}", 10);
      const boardCount = parseInt("{{ board }}", 10);
      const relationCount = parseInt("{{ relation.count }}", 10);
      const mentorCount = parseInt("{{ mentor.count }}", 10);

      animateValue("userCount", 0, userCount, 2000);
      animateValue("boardCount", 0, boardCount, 2000);
      animateValue("relationCount", 0, relationCount, 2000);
      animateValue("mentorCount", 0, mentorCount, 2000);
    }

    function animateValue(id, start, end, duration) {
      const range = end - start;
      const increment = end > start ? 1 : -1;
      const stepTime = Math.abs(Math.floor(duration / range));
      let current = start;
      const obj = document.getElementById(id);

      const timer = setInterval(function() {
        current += increment;
        obj.textContent = current;
        if (current == end) {
          clearInterval(timer);
        }
      }, stepTime);
    }

    var animationDelay = 1500;
    var lastAnimatedTime = 0;

    window.addEventListener("scroll", function() {
      var oTop = document.querySelector('.signup_list').offsetTop - window.innerHeight;
      var currentTime = new Date().getTime();

      if (window.scrollY > oTop && currentTime - lastAnimatedTime > animationDelay) {
        animateCounts();
        lastAnimatedTime = currentTime;
      }
    });
  });
</script>
{% endblock %}

project/main/templates/main/mentor_info.html
{% extends 'base_with_nav.html' %}
{% load static %}
{% block content %}

<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/main/mentor_info.css'%}"
/>

<div class='screen'>
  <div class="main">
    <div class="body"> 
      <div class='nav'>
        <div class="left" style="z-index: 1;">
          <a href="{% url 'main:mentor-list' %}">
            <img src="{% static 'images/arrow-24.png' %}" alt='but' width='32px'>
          </a>
        </div>
        <div class="right">
          <h2 class="color_28 title_text" style="text-align: center;">멘토 정보</h2>
        </div>
        <div style="width:32px;"></div>
      </div>
      <p class="color_28 title_text2">멘토 프로필</p>
      <div class="mentor_card_wrap">
        <div class="mentor_card">
          <div class="mentor_card_comp_font color_00">
            {{mentor.mentor_company}}
          </div> 
          <div class="mentor_card_dept_font color_00">
            {{mentor.mentor_dept}}
          </div> 
          <div class="centering">
            {% if mentor.user.profile.user_profile %}
              <img class="circuling" src="{{ mentor.user.profile.user_profile.url }}" alt="" width='100px' height='100px' style="padding-bottom: 20px;">
            {% else %}
              <img class="circuling" src="{% static 'images/logo.png' %}" width='100px' height='100px'>
            {% endif %}
            <div class="mentor_card_name_font color_00">
              {{mentor.user.profile.user_name}}
            </div> 
            <div class="mentor_card_major_font color_00">
              {{mentor.user.profile.user_major}}
            </div> 
            <div class="mentor_card_work_font color_9D">
              {{mentor.mentor_work}}
            </div>
            

            <!-- button 관련 바꾸어야함 뜨질 않아 -->
            <div class="row1"> 
              {% if request.user != mentor %}
              {% if user in mentor.followers.all %}
                <a href="{% url 'main:follow' mentor.id %}">
                  <button type="button"><img src="{% static 'images/unfollow.png' %}" width="36px" height="36px"></button>
                </a>
              {% else %}
                <a href="{% url 'main:follow' mentor.id %}">
                  <button type="button"><img src="{% static 'images/follow.png' %}" width="36px" height="36px"></button>
                </a>
              {% endif %}
            {% endif %}
            
          {% if request.user != mentor %}
              {% if user in mentor.mentor_ship.all %}
                <a href="{% url 'main:mentor-ask' mentor.id %}">
                  <button type="button" class="btn btn-outline-info font_1">멘토링 취소하기</button>
                </a>
              {% else %}
                <a href="{% url 'main:mentor-ask' mentor.id %}">
                  <button type="button" class="btn btn-info font_2">멘토링 신청하기</button>
                </a>
              {% endif %}
            {% endif %}
            </div>
            
          </div>
        </div>
      </div>
      <p class="color_28 title_text">한 줄 소개</p>
      <p class="color_00 context_text">{{ mentor.mentor_summary }}</p>
      <p class="color_28 title_text">멘토 소개</p>
      <p class="color_00 context_text">{{ mentor.mentor_info }}</p>
      <p class="color_28 title_text">멘토 이력</p>
      <p class="color_00 context_text">{{ mentor.mentor_career }}</p>
      <p class="color_28 title_text">멘토 자격증 / 어학 성적</p>
      <p class="color_00 context_text">{{ mentor.mentor_certificate }}</p>
      <!-- 태그로 가져와야함 -->
    </div>
  </div>
</div>

{% endblock %}

project/main/templates/main/mentor_start.html
{% extends 'base_with_nav.html' %} {% load static %} {% block content %} 
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/main/mentor_start.css'%}"
/>

<form action="{% url 'main:mentor-start' %}" method="post" class='container'>
  {% csrf_token %}
  <div class="small_nav">
    <div class="left" style="z-index: 1;">
      <a style="margin-left: 15px;" href="{% url 'main:mainpage' %}">
        <img src="{% static 'images/arrow-24.png' %}" width="32px" style="z-index: 30;">
      </a>
    </div>
    <h2 class="color_28 title_text" style="text-align: center;">멘토</h2>
    <div class="right" style="width: 32px;"></div>
  </div>
  <div class='pictureandsubmit'>
    <img class="picture" src="{% static 'images/Rectangle 3406.png' %}">
    <p class='textbig'>현직자 동문 멘토에게 <br>매칭 받아보세요 </p>
    <p class='textsmall'>취트키에서 매칭 평균 만족도는 9.3점!</p>
    <a href="{% url 'main:mentor-list' %}" class="submit">멘토 리스트보기</a>
    <a class="submit1">멘토 등록하기</a>
    <a href="{% url 'main:mentor-enroll' %}" class="submit1">멘토 등록하기</a>
  </div>

  <div class='cheatkey'>
    <img class='cheatkeyimages' src={% static "images/Group 1410-2.png" %}>
    <div class='cheatkeymessage'>CHEAT KEY</div>
  </div>

  <div class='ment1'>세심한 멘토링 및 취업 정보를 전해주는<br>
    <div class='ment2'>동국인을 위한 매칭 커리어 플랫폼</div>
  </div>

  <div class='pictureee'>
    <div class='picture1'>
      <img class='picture1_1' src={% static "images/Group 1411.png" %}>
      <div class='picture1_12'>
        <div class='picture1_11'>1대1 매칭 멘토<br><br></div>
        직접 원하는 멘토를 선택해서<br>
        1대1로 매칭되어 기업에 대해 원하는<br>
        내용을 물어볼 수 있어요.
      </div>
    </div>

    <div class='picture2'>
      <div class='picture2_22'>
        <div class='picture2_21'>검증된 멘토<br><br></div>
        동국대학교 학생 인증과<br>
        취트키 담당자 검토를 통해 현업에<br>
        재직중인 것이 검증된 멘토에요.
      </div>
      <img class='picture2_2' src={% static "images/Group 1411-2.png" %}>
    </div>

    <div class='picture3'>
      <img class='picture3_3' src={% static "images/Group 1411-3.png" %}>
      <div class='picture3_32'>
        <div class='picture3_31'>멘토 팔로우 & 등록<br><br></div>
        멘토를 팔로우하여 나의 리스트를<br>
        확인 할 수 있고, 취업을 한다면<br>
        나도 멘토로 등록할 수 있어요.
      </div>
    </div>
  </div>

  <div class='basemint'>

    <div class='basemintment'>취트키 멘토 매칭은 이렇게 운영됩니다.</div>
    <div class='sqare'>
      <div class='step1'>
        <div class='sqare1'>STEP<br>1</div>
        <div class='sqare_1'>멘토 선택</div>
        멘토를 선택하고,<br> 궁금한 내용에 대해 <br>글을 작성해주세요.
      </div>

      <div class='line'></div>

      <div class='step2'>
        <div class='sqare1'>STEP<br>2</div>
        <div class='sqare_2'>검토 후 회신</div>
        멘토가 글 검토 후<br> 매칭 진행 여부를<br> 안내드려요. 
      </div>

      <div class='line'></div>

      <div class='step3'>
        <div class='sqare1'>STEP<br>3</div>
        <div class='sqare_3'>매칭</div>
        멘토와 매칭되어<br> 채팅을 통해 자유롭게<br> 멘토링 할 수 있어요.
      </div>
    </div>
  </div>

  <div class='benefit'>
    <div class='benefit1'>등록된 멘토는 특별한 혜택이 있습니다.</div>
    <div class='benefit2'>*본 혜택은 멘토링을 3개월 내 1회 이상 멘토링을 진행했을 경우 제공되며, 만기시 자동으로 혜택이 해제됩니다.</div>
    <div class='benefit3'>“학생때 누렸던 혜택을 그대로 받아 볼 수 있습니다!”</div>
  </div>

  <div class='icon'>
    <div class='icon1'>📖<div class='icon1_1'>핫트랙스&교보문고 10% 할인</div></div>
    <div class='icon1'>🎬<div class='icon1_2'>대한 극장 7,000원 영화 관람<br>메가박스 동문점 3천원 할인</div></div>
    <div class='icon1'>☕<div class='icon1_2'>뚜레쥬르 제일제당사옥점 15% 할인<br>할리스 충무로역점 20% 할인</div></div>
    <div class='icon1'>🗂️<div class='icon1_2'>마이크로소프트 오피스 무료 이용<br>구글 드라이브 용량 무제한</div></div>
  </div>
  <div class="credit" style="margin-top: 2rem;">
    <div class="webname">
      <p class="webname_bold">CHEAT KEY</p>
      <p class="font_400">취트키 CHEAT KEY</p>
    </div>
    <div class="maker">
      <p class="font_500">Product Designer | 구도욱<br>Front End | 오태준, 최민<br>Back End | 박선우, 황채현</p>
    </div>
    <div class="instayoutube_icon"></div>
    <div class="copyright font_200">Copyright ⓒ 2024 심바오 Team. All Rights Reserved.</div>
  </div>
</form>

{% if error %}
<div style="color: red">{{ error }}</div>
{% endif %}
{% endblock %}